In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
 

In [47]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [48]:
print(x)

[['Budiman' 23.0 nan]
 ['Lala' 25.0 3.6]
 ['fariza' 24.0 3.1]
 ['Jino' nan 2.8]
 ['Jihana' 22.0 3.9]
 ['Fidit' 28.0 2.6]]


In [49]:
print(y)

['Lulus' 'Lulus' 'Lulus' 'Tidak Lulus' 'Lulus' 'Tidak Lulus']


In [52]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [54]:
print(x)

[['Budiman' 23.0 3.2]
 ['Lala' 25.0 3.6]
 ['fariza' 24.0 3.1]
 ['Jino' 24.4 2.8]
 ['Jihana' 22.0 3.9]
 ['Fidit' 28.0 2.6]]


In [56]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [57]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 23.0 3.2]
 [0.0 0.0 0.0 0.0 1.0 0.0 25.0 3.6]
 [0.0 0.0 0.0 0.0 0.0 1.0 24.0 3.1]
 [0.0 0.0 0.0 1.0 0.0 0.0 24.4 2.8]
 [0.0 0.0 1.0 0.0 0.0 0.0 22.0 3.9]
 [0.0 1.0 0.0 0.0 0.0 0.0 28.0 2.6]]


In [58]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [59]:
print(y)

[0 0 0 1 0 1]


In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [61]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 22.0 3.9]
 [1.0 0.0 0.0 0.0 0.0 0.0 23.0 3.2]
 [0.0 0.0 0.0 1.0 0.0 0.0 24.4 2.8]
 [0.0 1.0 0.0 0.0 0.0 0.0 28.0 2.6]]


In [62]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 24.0 3.1]
 [0.0 0.0 0.0 0.0 1.0 0.0 25.0 3.6]]


In [63]:
print(y_train)

[0 0 1 1]


In [64]:
print(y_test)

[0 0]


In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [66]:
print(x_train)

[[0.0 0.0 1.0 -0.5773502691896258 0.0 0.0 -1.0337787950042723
  1.5597792768225465]
 [1.0 0.0 0.0 -0.5773502691896258 0.0 0.0 -0.5938729247896886
  0.15094638162798954]
 [0.0 0.0 0.0 1.7320508075688774 0.0 0.0 0.021995293510727935
  -0.6541009870546154]
 [0.0 1.0 0.0 -0.5773502691896258 0.0 0.0 1.6056564262832298
  -1.056624671395917]]


In [67]:
print(x_test)

[[0.0 0.0 0.0 -0.5773502691896258 0.0 1.0 -0.1539670545751049
  -0.05031546054266169]
 [0.0 0.0 0.0 -0.5773502691896258 1.0 0.0 0.28593881563947876
  0.9559937503105936]]
